<x-restaurant-layout title="Tableau de bord" :admin="true">
<div class="section-heading"><div><p class="eyebrow">BONJOUR {{ mb_strtoupper(auth()->user()->first_name ?: auth()->user()->name) }}</p><h1>Prêts pour le service ?</h1></div><a class="button" href="{{ route('admin.slots') }}">Gérer les créneaux ↗</a></div>
<div class="notice" data-feed-url="{{ route('admin.feed') }}"><span data-feed-message>Les nouvelles commandes sont vérifiées automatiquement.</span><a href="{{ route('admin.orders', []) }}">Voir les commandes en préparation →</a></div>
@if($failedNotifications)<div class="notice error">{{ $failedNotifications }} notification(s) en attente d’envoi. Les commandes sont bien enregistrées.</div>@endif
<div class="stats-grid">@foreach($report['periods'] as $period)<article class="panel stat"><span class="eyebrow">{{ $period['label'] }}</span><strong>{{ number_format($period['revenue'] / 100, 2, ',', ' ') }} €</strong><span>{{ $period['count'] }} commandes</span><small>{{ $period['evolution'] === null ? 'Pas de comparaison disponible' : ($period['evolution'] >= 0 ? '+' : '').$period['evolution'].' % sur la période comparable' }}</small></article>@endforeach</div>
<p class="muted">Valeur des commandes non annulées, par date de création. Comparaison avec la même durée écoulée de la période précédente.</p>
<div class="service-grid"><section class="panel"><div class="section-heading"><h2>L’activité des 14 derniers jours</h2><span class="muted">Commandes en €</span></div><div class="bar-chart" role="img" aria-label="Valeur quotidienne des commandes ; données détaillées sous le graphique">@php($max = max(1, max(array_column($report['chart'], 'value'))))@foreach($report['chart'] as $point)<div class="bar-column" title="{{ $point['label'] }} : {{ number_format($point['value'] / 100, 2, ',', ' ') }} €"><div class="bar" style="height: {{ max(2, $point['value'] / $max * 100) }}%"></div><span>{{ $point['label'] }}</span></div>@endforeach</div><details><summary>Données du graphique</summary><table><thead><tr><th>Jour</th><th>Montant</th></tr></thead><tbody>@foreach($report['chart'] as $point)<tr><td>{{ $point['label'] }}</td><td>{{ number_format($point['value'] / 100, 2, ',', ' ') }} €</td></tr>@endforeach</tbody></table></details></section><section class="panel"><p class="eyebrow">LE SERVICE D’AUJOURD’HUI</p><h2>Au restaurant</h2><div class="metric-row"><span>Commandes en attente</span><strong>{{ $report['pending'] }}</strong></div><div class="metric-row"><span>Commandes retirées</span><strong>{{ $report['completed'] }}</strong></div><div class="metric-row"><span>Produits remis aux clients</span><strong>{{ $report['units'] }}</strong></div><div class="metric-row"><span>Encaissé aujourd’hui</span><strong>{{ number_format($report['cash'] / 100, 2, ',', ' ') }} €</strong></div><button class="button full secondary" data-enable-push data-key="{{ config('restaurant.vapid.public_key') }}" data-url="{{ route('admin.push.store') }}" @disabled(!$pushConfigured)>Activer les notifications sur cet appareil</button><p class="muted" data-push-status aria-live="polite">{{ $pushConfigured ? 'Autorisez les notifications pour être informé des nouvelles commandes.' : 'Les notifications de cet appareil seront disponibles après configuration du serveur.' }}</p></section></div>
@include('restaurant.admin.order-chart')
<div class="section-heading"><h2>Commandes à préparer</h2><a href="{{ route('admin.orders') }}">Toutes les commandes ↗</a></div><div class="order-list">@forelse($orders->sortBy(fn($order) => $order->slot->date->format('Y-m-d').$order->slot->starts_at) as $order)<a class="panel order-summary" href="{{ route('admin.orders.show', $order) }}"><div><span class="eyebrow">#{{ $order->id }} · {{ $order->slot->date->format('d/m') }}</span><h3>{{ substr($order->slot->starts_at, 0, 5) }} — {{ $order->customer_name }}</h3></div><span class="badge">{{ \App\Models\Order::STATUSES[$order->status] }}</span><strong>{{ number_format($order->total / 100, 2, ',', ' ') }} € ↗</strong></a>@empty<div class="panel"><p>Aucune commande en attente. Vous êtes à jour.</p></div>@endforelse</div>
</x-restaurant-layout>
