<x-restaurant-layout :title="$rule->exists ? 'Modifier la formule' : 'Créer une formule'" :admin="true">
<div class="section-heading"><div><p class="eyebrow">UNE FORMULE À VOTRE IMAGE</p><h1>{{ $rule->exists ? 'Modifier '.$rule->label() : 'Créer une formule' }}</h1></div><a href="{{ route('admin.menu-rules') }}">← Les formules</a></div>
<form method="post" action="{{ route('admin.menu-rules.save', $rule->exists ? $rule->id : null) }}" class="checkout-grid" data-formula-admin>@csrf
<section class="panel"><h2>Présentation et prix</h2><label>Nom de la formule<input name="name" value="{{ old('name', $rule->name) }}" required maxlength="255" placeholder="Menu du chef gourmand"></label><label>Description<textarea name="description" rows="3" maxlength="5000">{{ old('description', $rule->description) }}</textarea></label><label>Prix fixe en euros<input name="price" inputmode="decimal" value="{{ old('price', number_format($rule->price / 100, 2, '.', '')) }}" required></label><p class="muted">Le prix couvre tous les produits de la formule. Pour les tests, le prix initial est de 20 €.</p><label>Ordre d’affichage<input name="position" type="number" min="0" max="999" value="{{ old('position', $rule->position) }}" required></label>
<input type="hidden" name="available" value="0"><label class="checkbox-label"><input type="checkbox" name="available" value="1" @checked(old('available', $rule->available))> Formule active</label><p class="muted">Une formule inactive ne peut plus être commandée ni proposée en conversion.</p>
<input type="hidden" name="visible" value="0"><label class="checkbox-label"><input type="checkbox" name="visible" value="1" @checked(old('visible', $rule->visible))> Visible dans l’onglet Menus</label><p class="muted">Une formule masquée mais active reste accessible par son lien et peut être proposée si elle fait économiser sur le panier.</p>
</section>
<section class="panel"><h2>Catégories de la formule</h2><p>Un produit par catégorie. Choisissez un plat classique <em>ou</em> un plat du chef ; les formules sans plat sont aussi possibles.</p><fieldset><legend class="sr-only">Catégories incluses</legend><div class="menu-category-grid">@foreach(\App\Services\DynamicMenuService::CATEGORIES as $code)<label class="menu-category"><input type="checkbox" name="categories[]" value="{{ $code }}" @checked(in_array($code, old('categories', $rule->exists ? $rule->categories() : [])))> {{ \App\Models\Category::LABELS[$code] }}</label>@endforeach</div></fieldset>
<p class="notice" data-formula-side-note aria-live="polite">Plat classique : accompagnement ajouté automatiquement. Plat du chef : garniture déjà incluse, aucun choix séparé.</p><button class="button full">Enregistrer la formule</button></section>
</form></x-restaurant-layout>
